service: UploadCodeEZDUMP

	
provider:
  name: aws
  runtime: nodejs12.x
  stage: development
  profile: devProfile
  # Provide permissions for this service to manipulate S3.
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::test-bucket-ezdumptruck/*"

package:
  exclude:
    - node_modules/**
    - .github/**
    - .idea/**
    - .vscode/** 
    - types/**
    - test/**
    - .eslintrc.js
    - .prettierrc
    - nest-cli.json
    - README.md
    - tsconfig.build.json
    - tsconfig.json
    - yarn.lock

# Expose function to public API for POST requests.
functions:
  users:
    handler: users.handler
    events:
      - s3:
          bucket: test-bucket-ezdumptruck
          event: s3:ObjectCreated:*
          existing: true

# Give service access to the specific S3 bucket.
resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: test-bucket-ezdumptruck
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
            - GET
            - PUT
            - POST
            - HEAD
            AllowedOrigins:
            - "*"
            AllowedHeaders:
            - "*"