export enum DriverStatus {
  CLOCKED_IN = 'CLOCKED_IN',
  INACTIVE = 'INACTIVE',
  BREAK = 'BREAK',
  NOT_CLOCKED_IN = 'NOT_CLOCKED_IN',
  ACTIVE = 'ACTIVE',
  IS_DISABLE = 'IS_DISABLE',
  IS_RESTRICTED = 'IS_RESTRICTED'
}
