export enum TruckSubType {
  ALUMINUM_BED = 'ALUMINUM_BED',
  STEEL_BED_BARN_DOOR = 'STEEL_BED_BARN_DOOR',
  STEEL_BED_HIGH_LIFT_GATE = 'STEEL_BED_HIGH_LIFT_GATE',
  STEEL_BED_REGULAR_GATE = 'STEEL_BED_REGULAR_GATE',
  BED_WITH_VIBRATOR = 'BED_WITH_VIBRATOR',

  STEEL = 'STEEL',
  ALUMINUM = 'ALUMINUM',
  WITH_HIGH_LIFT_GATE = 'WITH_HIGH_LIFT_GATE',
  WITH_BARN_DOOR = 'WITH_BARN_DOOR',
  WITH_VIBRATOR = 'WITH_VIBRATOR',
  ABLE_TO_DO_ASPHALT = 'ABLE_TO_DO_ASPHALT',
}
